import { User } from '../models/user.model.js';
import { HttpError } from '../utilities/http-error.js';
export type TemplateAccess = 'free' | 'premium';
export type TemplateDefinition = {
  id: string;
  name: string;
  description: string;
  accessLevel: TemplateAccess;
  category: 'modern' | 'professional' | 'minimal' | 'creative';
  layout: 'single-column' | 'two-column';
  atsFriendly: boolean;
  recommendedFor: string[];
  palettes: Array<{
    name: string;
    primaryColor: string;
    secondaryColor: string;
    headingColor: string;
    textColor: string;
  }>;
  fonts: string[];
  featured: boolean;
  popular: number;
  active: boolean;
  sortOrder: number;
  defaultStyling: Record<string, unknown>;
};
const p = (
  name: string,
  primaryColor: string,
  secondaryColor: string,
  headingColor = primaryColor,
  textColor = '#1e293b',
) => ({ name, primaryColor, secondaryColor, headingColor, textColor });
const base = {
  pageSize: 'A4',
  fontSize: 10,
  lineHeight: 1.45,
  sectionSpacing: 14,
  pageMargin: 18,
  showProfileImage: false,
  showIcons: true,
  dateFormat: 'MMM YYYY',
  sectionTitleStyle: 'underline',
};
export const templateRegistry: TemplateDefinition[] = [
  {
    id: 'modern-classic',
    name: 'Modern Classic',
    description: 'Clean navy hierarchy and fine dividers.',
    accessLevel: 'free',
    category: 'modern',
    layout: 'single-column',
    atsFriendly: true,
    recommendedFor: ['General', 'Operations', 'Sales'],
    palettes: [p('Navy', '#16324f', '#e8eef4'), p('Indigo', '#4338ca', '#eef2ff')],
    fonts: ['Inter', 'Arial'],
    featured: true,
    popular: 100,
    active: true,
    sortOrder: 1,
    defaultStyling: {
      ...base,
      layout: 'single-column',
      fontFamily: 'Inter',
      primaryColor: '#16324f',
      secondaryColor: '#e8eef4',
      headingColor: '#16324f',
      textColor: '#1e293b',
      headingSize: 14,
    },
  },
  {
    id: 'professional',
    name: 'Professional',
    description: 'Traditional corporate structure and formal type.',
    accessLevel: 'free',
    category: 'professional',
    layout: 'single-column',
    atsFriendly: true,
    recommendedFor: ['Finance', 'Management', 'Administration'],
    palettes: [p('Charcoal', '#334155', '#f1f5f9')],
    fonts: ['Georgia', 'Arial'],
    featured: true,
    popular: 92,
    active: true,
    sortOrder: 2,
    defaultStyling: {
      ...base,
      layout: 'single-column',
      fontFamily: 'Georgia',
      primaryColor: '#334155',
      secondaryColor: '#f1f5f9',
      headingColor: '#111827',
      textColor: '#1f2937',
      headingSize: 15,
    },
  },
  {
    id: 'minimal',
    name: 'Minimal',
    description: 'Airy composition with quiet typography.',
    accessLevel: 'free',
    category: 'minimal',
    layout: 'single-column',
    atsFriendly: true,
    recommendedFor: ['Entry Level', 'Research', 'Education'],
    palettes: [p('Ink', '#111827', '#ffffff')],
    fonts: ['Inter', 'Arial'],
    featured: false,
    popular: 84,
    active: true,
    sortOrder: 3,
    defaultStyling: {
      ...base,
      layout: 'single-column',
      fontFamily: 'Inter',
      primaryColor: '#111827',
      secondaryColor: '#ffffff',
      headingColor: '#111827',
      textColor: '#374151',
      headingSize: 13,
      sectionTitleStyle: 'plain',
    },
  },
  {
    id: 'technical',
    name: 'Technical',
    description: 'Skills and project-forward developer layout.',
    accessLevel: 'free',
    category: 'modern',
    layout: 'single-column',
    atsFriendly: true,
    recommendedFor: ['Engineering', 'DevOps', 'QA', 'IT'],
    palettes: [p('Terminal', '#0f766e', '#ccfbf1')],
    fonts: ['Roboto Mono', 'Inter'],
    featured: true,
    popular: 96,
    active: true,
    sortOrder: 4,
    defaultStyling: {
      ...base,
      layout: 'single-column',
      fontFamily: 'Roboto Mono',
      primaryColor: '#0f766e',
      secondaryColor: '#ccfbf1',
      headingColor: '#115e59',
      textColor: '#134e4a',
      headingSize: 13,
    },
  },
  {
    id: 'executive-pro',
    name: 'Executive Pro',
    description: 'Leadership-first editorial composition.',
    accessLevel: 'premium',
    category: 'professional',
    layout: 'single-column',
    atsFriendly: true,
    recommendedFor: ['Executives', 'Directors'],
    palettes: [p('Midnight', '#172554', '#fef3c7')],
    fonts: ['Merriweather', 'Georgia'],
    featured: true,
    popular: 95,
    active: true,
    sortOrder: 5,
    defaultStyling: {
      ...base,
      layout: 'single-column',
      fontFamily: 'Merriweather',
      primaryColor: '#172554',
      secondaryColor: '#fef3c7',
      headingColor: '#172554',
      textColor: '#1f2937',
      headingSize: 17,
    },
  },
  {
    id: 'modern-sidebar',
    name: 'Modern Sidebar',
    description: 'Structured sidebar for skills and contact details.',
    accessLevel: 'premium',
    category: 'modern',
    layout: 'two-column',
    atsFriendly: false,
    recommendedFor: ['Marketing', 'Operations'],
    palettes: [p('Cobalt', '#1d4ed8', '#dbeafe')],
    fonts: ['Inter'],
    featured: true,
    popular: 90,
    active: true,
    sortOrder: 6,
    defaultStyling: {
      ...base,
      layout: 'two-column',
      fontFamily: 'Inter',
      primaryColor: '#1d4ed8',
      secondaryColor: '#dbeafe',
      headingColor: '#1e3a8a',
      textColor: '#1e293b',
      headingSize: 14,
    },
  },
  {
    id: 'creative-studio',
    name: 'Creative Studio',
    description: 'Expressive asymmetric hierarchy with readable content.',
    accessLevel: 'premium',
    category: 'creative',
    layout: 'two-column',
    atsFriendly: false,
    recommendedFor: ['Design', 'Creative'],
    palettes: [p('Berry', '#9d174d', '#fce7f3')],
    fonts: ['Inter', 'Georgia'],
    featured: false,
    popular: 80,
    active: true,
    sortOrder: 7,
    defaultStyling: {
      ...base,
      layout: 'two-column',
      fontFamily: 'Inter',
      primaryColor: '#9d174d',
      secondaryColor: '#fce7f3',
      headingColor: '#831843',
      textColor: '#3f3f46',
      headingSize: 18,
      sectionTitleStyle: 'filled',
    },
  },
  {
    id: 'elegant-serif',
    name: 'Elegant Serif',
    description: 'Refined editorial typography and restrained detail.',
    accessLevel: 'premium',
    category: 'professional',
    layout: 'single-column',
    atsFriendly: true,
    recommendedFor: ['Consulting', 'Legal'],
    palettes: [p('Burgundy', '#7f1d1d', '#fef2f2')],
    fonts: ['Merriweather', 'Georgia'],
    featured: false,
    popular: 82,
    active: true,
    sortOrder: 8,
    defaultStyling: {
      ...base,
      layout: 'single-column',
      fontFamily: 'Merriweather',
      primaryColor: '#7f1d1d',
      secondaryColor: '#fef2f2',
      headingColor: '#450a0a',
      textColor: '#292524',
      headingSize: 16,
    },
  },
  {
    id: 'product-leader',
    name: 'Product Leader',
    description: 'Impact-led sections optimized for product outcomes.',
    accessLevel: 'premium',
    category: 'modern',
    layout: 'two-column',
    atsFriendly: true,
    recommendedFor: ['Product', 'Leadership'],
    palettes: [p('Violet', '#6d28d9', '#ede9fe')],
    fonts: ['Inter'],
    featured: true,
    popular: 91,
    active: true,
    sortOrder: 9,
    defaultStyling: {
      ...base,
      layout: 'two-column',
      fontFamily: 'Inter',
      primaryColor: '#6d28d9',
      secondaryColor: '#ede9fe',
      headingColor: '#4c1d95',
      textColor: '#27272a',
      headingSize: 15,
    },
  },
  {
    id: 'developer-pro',
    name: 'Developer Pro',
    description: 'Technical stack, projects, and links take priority.',
    accessLevel: 'premium',
    category: 'modern',
    layout: 'two-column',
    atsFriendly: true,
    recommendedFor: ['Software Engineering'],
    palettes: [p('Code Blue', '#0369a1', '#e0f2fe')],
    fonts: ['Roboto Mono', 'Inter'],
    featured: true,
    popular: 98,
    active: true,
    sortOrder: 10,
    defaultStyling: {
      ...base,
      layout: 'two-column',
      fontFamily: 'Roboto Mono',
      primaryColor: '#0369a1',
      secondaryColor: '#e0f2fe',
      headingColor: '#0c4a6e',
      textColor: '#172554',
      headingSize: 13,
    },
  },
  {
    id: 'international',
    name: 'International',
    description: 'Globally familiar structure with flexible dates.',
    accessLevel: 'premium',
    category: 'minimal',
    layout: 'single-column',
    atsFriendly: true,
    recommendedFor: ['International', 'Academic'],
    palettes: [p('Global', '#047857', '#d1fae5')],
    fonts: ['Arial', 'Inter'],
    featured: false,
    popular: 78,
    active: true,
    sortOrder: 11,
    defaultStyling: {
      ...base,
      layout: 'single-column',
      fontFamily: 'Arial',
      primaryColor: '#047857',
      secondaryColor: '#d1fae5',
      headingColor: '#065f46',
      textColor: '#1f2937',
      headingSize: 14,
    },
  },
  {
    id: 'compact-pro',
    name: 'Compact Pro',
    description: 'Dense but legible layout for substantial experience.',
    accessLevel: 'premium',
    category: 'professional',
    layout: 'two-column',
    atsFriendly: true,
    recommendedFor: ['Experienced', 'Consulting'],
    palettes: [p('Graphite', '#374151', '#e5e7eb')],
    fonts: ['Arial', 'Inter'],
    featured: false,
    popular: 86,
    active: true,
    sortOrder: 12,
    defaultStyling: {
      ...base,
      layout: 'two-column',
      fontFamily: 'Arial',
      primaryColor: '#374151',
      secondaryColor: '#e5e7eb',
      headingColor: '#111827',
      textColor: '#1f2937',
      headingSize: 12,
      fontSize: 9,
      sectionSpacing: 9,
      pageMargin: 12,
    },
  },
];
export const findTemplate = (id: string) => templateRegistry.find((t) => t.id === id);
export async function entitlement(userId: string) {
  const u = await User.findById(userId)
    .select('plan subscriptionStatus subscriptionExpiresAt')
    .lean();
  const entitled =
    u?.plan === 'pro' &&
    ['active', 'trialing'].includes(u.subscriptionStatus) &&
    (!u.subscriptionExpiresAt || u.subscriptionExpiresAt > new Date());
  return {
    plan: u?.plan ?? 'free',
    premium: Boolean(entitled),
    expiresAt: u?.subscriptionExpiresAt,
  };
}
export async function assertAccess(userId: string, t: TemplateDefinition) {
  if (t.accessLevel === 'premium' && !(await entitlement(userId)).premium)
    throw new HttpError(
      403,
      'PREMIUM_REQUIRED',
      'An active Pro subscription is required to apply this template.',
    );
}
